#!/bin/bash

# Installing zgen, plugin manager
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

# colorls
gem install colorls

# vim-plug for neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

