#!bin/bash

# LunarVim dependencies
brew install python lazygit

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash